// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AllocationsController from "./allocations_controller"
application.register("allocations", AllocationsController)

import ArrowKeysNavigationController from "./arrow_keys_navigation_controller"
application.register("arrow-keys-navigation", ArrowKeysNavigationController)

import FlatpickrController from "./flatpickr_controller"
application.register("flatpickr", FlatpickrController)

import FormKeyPressController from "./form_key_press_controller"
application.register("form-key-press", FormKeyPressController)

import FormSubmissionController from "./form_submission_controller"
application.register("form-submission", FormSubmissionController)

import HotwireAnimationsController from "./hotwire_animations_controller"
application.register("hotwire-animations", HotwireAnimationsController)

import ModalsController from "./modals_controller"
application.register("modals", ModalsController)

import PortfolioAnalyzerChartController from "./portfolio_analyzer_chart_controller"
application.register("portfolio-analyzer-chart", PortfolioAnalyzerChartController)

import RemovalsController from "./removals_controller"
application.register("removals", RemovalsController)

import TooltipController from "./tooltip_controller"
application.register("tooltip", TooltipController)
