inherit_from: .rubocop_todo.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'Gemfile'
    - 'Guardfile'
    - 'Rakefile'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'node_modules/**/*'

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Max: 150

Metrics/MethodLength:
  Max: 40

Layout/LineLength:
  Max: 130

Lint/MissingSuper:
  Exclude:
    - 'app/services/**/*'

# These auto-corrections break functionality:
# - FormatStringToken: %{...} tokens are used in gsub, not sprintf
# - MemoizedInstanceVariableName: @allocation0 conflicts with store_accessor
# - HashTransformValues: original uses Hash[] from map.collect on key-value pairs
Style/FormatStringToken:
  Exclude:
    - 'app/helpers/bot_helper.rb'

Naming/MemoizedInstanceVariableName:
  Exclude:
    - 'app/models/bots/dca_dual_asset/marketcap_allocatable.rb'

Style/HashTransformValues:
  Exclude:
    - 'app/services/exchange_api/markets/kraken/market.rb'
