AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'Gemfile'
    - 'Guardfile'
    - 'Rakefile'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'node_modules/**/*'

# Metrics — disabled, not worth enforcing on existing codebase
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false

# Layout
Layout/LineLength:
  Max: 150
  AllowedPatterns:
    - '^  #'

# Style — disabled
Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/NegatedIf:
  Enabled: false
Style/EmptyElse:
  Enabled: false

# Style — auto-corrections that break functionality
Style/FormatStringToken:
  Exclude:
    - 'app/helpers/bot_helper.rb'
Style/HashTransformValues:
  Exclude:
    - 'app/services/exchange_api/markets/kraken/market.rb'

# Naming
Naming/AccessorMethodName:
  Enabled: false
Naming/MemoizedInstanceVariableName:
  Exclude:
    - 'app/models/bots/dca_dual_asset/marketcap_allocatable.rb'

# Style — disabled
Style/FetchEnvVar:
  Enabled: false
Style/SuperArguments:
  Enabled: false
Style/ArgumentsForwarding:
  Enabled: false
Style/CollectionQuerying:
  Enabled: false
Style/ComparableBetween:
  Enabled: false
Style/SafeNavigationChainLength:
  Enabled: false
Style/MultilineBlockChain:
  Enabled: false

# Naming — disabled
Naming/BlockForwarding:
  Enabled: false
Naming/PredicateMethod:
  Enabled: false
Naming/PredicatePrefix:
  Enabled: false

# Lint
Lint/DuplicateBranch:
  Enabled: false
Lint/NoReturnInBeginEndBlocks:
  Enabled: false
Lint/UselessConstantScoping:
  Enabled: false
Lint/MissingSuper:
  Exclude:
    - 'app/services/**/*'
    - 'app/models/clients/coingecko.rb'
    - 'app/models/clients/market_data.rb'
    - 'lib/result.rb'
