# secret_key_base is the sole root of ActiveRecord Encryption in this app (see
# config/initializers/active_record_encryption.rb), so a weak one means every stored
# exchange credential is decryptable and session cookies are forgeable. So warn loudly
# on every production boot; see the note above the check below for why this must not abort.
module SecretKeyBaseGuard
  # EXACT matches only. A substring match would abort every Umbrel container, which
  # legitimately runs on "${APP_SEED}-secret-key-base" (deltabadger/docker-compose.yml:24).
  KNOWN_PLACEHOLDERS = %w[
    dev-secret-key-not-for-production
    placeholder
    changeme
    secret
  ].freeze

  # Deliberately below the 128 chars `openssl rand -hex 64` produces: the bar is
  # "not obviously a typed-in word", not "matches our preferred generator". Raising it
  # would lock out existing installs whose working secret is merely shorter than ours.
  MINIMUM_LENGTH = 32

  # This message is for the one case that is an actual incident: the secret is a value
  # published in this repository, so every install that ever copied it shares a key that
  # anybody can read. The recipe below is deliberately clear-and-reissue rather than
  # re-encryption: re-encrypting in place would preserve credentials that are already
  # exposed in any leaked copy of the database, which does not fix anything.
  PUBLISHED_WARNING = <<~MESSAGE.freeze
    ================================ SECURITY WARNING ================================
    SECRET_KEY_BASE is a value published in the public repository.

    It is the encryption key for EVERYTHING encrypted in this instance: exchange API
    keys, your two-factor secret, withdrawal addresses, and market-data configuration.
    Anyone with a copy of this database can already read every credential in it. Deleting
    them here does NOT invalidate them — they must be revoked at their source.

    In this order:

      1. Stop the app.  docker compose stop
      2. Back up your storage directory, now that nothing is writing to it.
      3. List what is stored:
           docker compose run --rm --no-deps deltabadger \\
             rake deltabadger:encryption:report
         Copy your withdrawal addresses — they are not recoverable afterwards.
      4. REVOKE everything it listed, at its source: exchange API keys, fee keys, SMTP
         password, Alpaca key and secret, CoinGecko key, market-data token. Revoke only
         — replacements have nowhere to live until step 7.
      5. Clear what is stored:
           docker compose run --rm --no-deps -e CONFIRM=clear-credentials \\
             deltabadger rake deltabadger:encryption:reset
      6. Blank the SECRET_KEY_BASE line in .env.docker.
      7. Start the app. A strong per-install secret is generated for you.
      8. Sign in, issue fresh credentials, add them, and re-enable two-factor.

    Interactive Brokers is the slow one: its key pair is generated by this app and stored
    here, so it can only be replaced after step 7 — run the connect wizard again, register
    the new key in IBKR's portal, and wait for them to activate it.

    Do NOT just change the value on its own — every encrypted field derives from it, so
    that alone makes your two-factor secret unreadable and locks you out.
    ==================================================================================
  MESSAGE

  # Reached only by a secret that is merely SHORT — privately generated, never published.
  # Nothing is known to be exposed, so this must not read like an incident: no "anyone can
  # read your data", no instruction to revoke. The fix is the same procedure, at leisure.
  SHORT_WARNING = <<~MESSAGE.freeze
    ================================ SECURITY NOTICE =================================
    SECRET_KEY_BASE is shorter than #{MINIMUM_LENGTH} characters.

    It is the encryption key for everything encrypted in this instance, and a short one
    is easier to guess than it should be. This is not an exposure — your value was not
    published anywhere — so there is no urgency.

    When convenient, move to a stronger secret. Because every encrypted field derives
    from it, you cannot simply change the value: see the recovery steps in the README
    under "Moving to a new SECRET_KEY_BASE". They clear the stored credentials, which
    you then re-enter.
    ==================================================================================
  MESSAGE

  # Published in this repository, so every install that copied it shares one key that
  # anybody can read. This is a compromise, not a weakness.
  def self.published?(secret)
    KNOWN_PLACEHOLDERS.include?(secret.to_s)
  end

  # Shorter than we would like, but privately generated. Worth improving, not an incident.
  def self.short?(secret)
    secret.to_s.length < MINIMUM_LENGTH
  end

  def self.weak?(secret)
    published?(secret) || short?(secret)
  end

  def self.warning_for(secret)
    return PUBLISHED_WARNING if published?(secret)
    return SHORT_WARNING if short?(secret)

    nil
  end

  # Extracted from the boot branch below purely so it can be tested. Left inline, a
  # regression that swapped warning_for back to weak? + PUBLISHED_WARNING would pass every
  # test and quietly tell an operator with a short private secret that their database is
  # readable by anyone.
  #
  # `if logger` rather than `logger&.error` — no behavioral difference on this single call,
  # but safe navigation on a logger elsewhere in this codebase has previously produced a
  # silent no-op, so the explicit conditional is preferred here as a matter of habit. Being
  # explicit costs nothing.
  def self.emit_warning!(secret, logger: Rails.logger)
    warning = warning_for(secret)
    return nil if warning.nil?

    logger.error(warning) if logger # rubocop:disable Style/SafeNavigation -- see comment above
    warn(warning)
    warning
  end
end

# WARN, do not abort. An existing install running on the weak secret still has
# readable data; aborting its boot would strand it with no way to migrate.
#
# Skipped during `assets:precompile`, which Rails runs with a generated dummy secret.
# rubocop:disable Style/IfUnlessModifier -- block form keeps `if Rails.env.production?`
# ahead of the emit_warning! call, which test/config/secret_key_base_guard_test.rb
# relies on to locate this branch by source text.
if Rails.env.production? && ENV['SECRET_KEY_BASE_DUMMY'].blank?
  SecretKeyBaseGuard.emit_warning!(Rails.application.secret_key_base)
end
# rubocop:enable Style/IfUnlessModifier
